[project]
name = "decision-tree"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13.8"
dependencies = [
    "ipykernel>=7.1.0",
    "kaleido>=1.2.0",
    "nbformat>=5.10.4",
    "pandas>=2.3.3",
    "pingouin>=0.5.5",
    "plotly>=6.5.0",
    "scikit-learn>=1.7.2",
]
